Insert absolute imports before relative imports
bitkompagniet/vscode_extension_quick_require pull request #11
Opened 2017-04-07 17:36 UTC by nickyhajal

This should resolve issue #8.

It makes sure that absolute imports (core modules & external dependencies) are placed together, above local imports.

To accomplish this, it passes whether the import is external to `get-position`. In `get-position` we have a bit of new logic + a new function to test if a line in a code block is an external or local import (`isLocalRequire`).

I also had to add an `isRequire` test in `extension.js` to determine if an additional line-break should be added after the new import (since we don't want one when adding a new external import above an existing local import).

I wasn't sure if you'd prefer to duplicate that function or pull it into its own file for reuse.

2017-04-07 17:36 UTC, nickyhajal commented on src/extension.js
> +function isRequire(line) {
Should this be pulled into it's own file to prevent duplication between here and get-position?

2017-04-21 09:25 UTC, kparkov requested changes
I like it. But I think it is a good idea to refactor the code to prevent duplication.

2017-04-21 09:25 UTC, kparkov commented on src/extension.js
> +function isRequire(line) {
I think that is a really good idea.

2017-04-21 18:20 UTC, nickyhajal commented
Just pushed an update that should take care of that!

2017-04-23 19:13 UTC, kparkov approved these changes

2017-06-12 10:06 UTC, kparkov approved these changes
Love it. It's accepted. Sorry about the loooong delay. We were very busy in the business.

2017-06-12 10:06 UTC, merged